const app=document.querySelector('#app');let current=null,mode=null,deck=[],i=0,score=0,answered=false,grammarKey=null;
const shuffle=a=>[...a].sort(()=>Math.random()-.5);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const norm=s=>s.toLowerCase().trim().replace(/[.!?]/g,'').replace(/[’‘]/g,"'").replace(/\s+/g,' ');const noArticle=s=>norm(s).replace(/^(the|a|an|der|die|das|den|dem|ein|eine|einen|einem|einer)\s+/,'');const variants=s=>s.split(/[;/]/).map(x=>norm(x.replace(/\([^)]*\)/g,'').trim())).filter(Boolean);function ok(input,target){let n=norm(input),na=noArticle(input);return variants(target).some(v=>n===v||na===noArticle(v))||norm(target)===n||noArticle(target)===na}
function save(id,val){localStorage.setItem('ep-'+id,JSON.stringify(val))}function load(id){try{return JSON.parse(localStorage.getItem('ep-'+id))||{seen:0,good:0}}catch{return{seen:0,good:0}}}
function crumbs(extra=''){return `<div class="crumbs"><button onclick="home()">Year 5</button><span>›</span><button onclick="unit4()">Unit 4 · Where I live</button>${extra}</div>`}
function home(){location.hash='';app.innerHTML=`<section class="hero"><h1>English Practice</h1><p>Choose a unit and practise at your own pace.</p></section><h2 class="section-title">Year 5</h2><div class="grid"><article class="card" onclick="unit4()"><span class="num">UNIT 4</span><h3>Where I live</h3><p class="small">Vocabulary & grammar</p></article><article class="card" style="opacity:.55"><span class="num">UNIT 5</span><h3>Around the year</h3><p class="small">Coming next · Lists #20–#24</p></article></div>`}
function unit4(){location.hash='unit4';app.innerHTML=crumbs('').replace(/<span>›<\/span><button[^>]*>Unit 4[^<]*<\/button>/,'')+`<section class="hero"><h1>Unit 4</h1><p>Where I live · Vocabulary and grammar for your LWL.</p></section><h2 class="section-title">Vocabulary</h2><div class="grid">${Object.entries(VOCAB).map(([id,l])=>{let p=load(id),pct=p.seen?Math.round(p.good/p.seen*100):0;return `<article class="card" onclick="openList('${id}')"><span class="num">LIST #${id}</span><h3>${esc(l.title)}</h3><p class="small">${l.words.length} words · ${esc(l.range)}</p><div class="progress"><i style="width:${pct}%"></i></div></article>`}).join('')}</div><h2 class="section-title">Grammar</h2><div class="grid"><article class="card" onclick="openGrammar('prep')"><span class="num">GRAMMAR</span><h3>Prepositions</h3><p class="small">Place & movement · Fill in the gap</p></article><article class="card" onclick="openGrammar('directions')"><span class="num">GRAMMAR</span><h3>Giving directions</h3><p class="small">Useful phrases · Fill in the gap</p></article></div>`}
function openGrammar(key){grammarKey=key;location.hash='grammar-'+key;let g=GRAMMAR[key],p=load('g-'+key),pct=p.seen?Math.round(p.good/p.seen*100):0;app.innerHTML=crumbs(`<span>›</span><b>${esc(g.title)}</b>`)+`<section class="hero"><h1>${esc(g.title)}</h1><p>${esc(g.intro)}</p></section><div class="grid"><button class="mode" onclick="startGrammar()"><span class="icon">✏️</span><b>Start practice</b><span class="small">${g.tasks.length} gap-fill questions</span></button><div class="mode"><span class="icon">📈</span><b>Your practice score</b><span class="small">${p.seen?`${pct}% correct so far`:'No practice yet'}</span><div class="progress"><i style="width:${pct}%"></i></div></div></div>`}
function startGrammar(){i=0;score=0;answered=false;deck=shuffle(GRAMMAR[grammarKey].tasks);renderGrammar()}
function renderGrammar(){if(i>=deck.length)return finishGrammar();let t=deck[i];app.innerHTML=crumbs(`<span>›</span><button onclick="openGrammar('${grammarKey}')">Grammar</button><span>›</span><b>Practice</b>`)+`<div class="practice"><div class="status"><span>${i+1} / ${deck.length}</span><span>✓ ${score}</span></div><section class="question"><div class="small">Fill in the gap</div><div class="prompt">${esc(t.q)}</div><div class="small">Hint: ${esc(t.hint)}</div><input id="gans" class="input" autocomplete="off" autocapitalize="off" placeholder="Type the missing word(s)…" onkeydown="if(event.key==='Enter')checkGrammar()"><div id="feedback"></div><div class="controls"><button class="btn" onclick="checkGrammar()">Check</button></div></section></div>`;setTimeout(()=>document.querySelector('#gans')?.focus(),0)}
function checkGrammar(){if(answered){i++;answered=false;return renderGrammar()}answered=true;let t=deck[i],input=document.querySelector('#gans').value,g=norm(input)===norm(t.a);let p=load('g-'+grammarKey);p.seen++;if(g){p.good++;score++}save('g-'+grammarKey,p);document.querySelector('#feedback').innerHTML=`<div class="answer">${g?'✓ Correct!':'Not quite.'}</div>${g?'':`<div class="small">Correct answer: <b>${esc(t.a)}</b></div>`}`;document.querySelector('.controls').innerHTML=`<button class="btn" onclick="checkGrammar()">Next</button>`}
function finishGrammar(){let pct=Math.round(score/deck.length*100);app.innerHTML=crumbs(`<span>›</span><button onclick="openGrammar('${grammarKey}')">Grammar</button>`)+`<div class="practice"><section class="question result"><div class="small">Finished!</div><div class="score">${pct}%</div><h2>${pct>=80?'Great job!':'Keep practising!'}</h2><p>${score} of ${deck.length} correct</p><div class="controls"><button class="btn" onclick="startGrammar()">Try again</button><button class="btn secondary" onclick="unit4()">Back to Unit 4</button></div></section></div>`}
function openList(id){current=id;location.hash='list-'+id;let l=VOCAB[id];app.innerHTML=crumbs(`<span>›</span><b>List #${id}</b>`)+`<section class="hero"><h1>List #${id}</h1><p>${esc(l.title)} · ${l.words.length} words</p></section><h2 class="section-title">How do you want to practise?</h2><div class="grid"><button class="mode" onclick="start('cards')"><span class="icon">🃏</span><b>Flashcards</b><span class="small">Look, flip, remember.</span></button><button class="mode" onclick="start('de-en')"><span class="icon">🇩🇪</span><b>German → English</b><span class="small">Type the English word.</span></button><button class="mode" onclick="start('en-de')"><span class="icon">🇬🇧</span><b>English → German</b><span class="small">Type the German word.</span></button><button class="mode" onclick="start('choice')"><span class="icon">🎯</span><b>Choose</b><span class="small">Pick the right answer.</span></button><button class="mode" onclick="start('match')"><span class="icon">🔀</span><b>Match</b><span class="small">Find the pairs.</span></button><button class="mode" onclick="start('test')"><span class="icon">🏆</span><b>Test yourself</b><span class="small">10 mixed questions.</span></button></div>`}
function start(m){mode=m;i=0;score=0;answered=false;deck=shuffle(VOCAB[current].words);if(m==='test')deck=deck.slice(0,10);if(m==='match')return match();renderQ()}
function shell(body){app.innerHTML=crumbs(`<span>›</span><button onclick="openList('${current}')">List #${current}</button><span>›</span><b>Practice</b>`)+`<div class="practice"><div class="status"><span>${Math.min(i+1,deck.length)} / ${deck.length}</span><span>✓ ${score}</span></div>${body}</div>`}
function renderQ(){if(i>=deck.length)return finish();let [en,de]=deck[i],prompt=mode==='de-en'?de:en,target=mode==='de-en'?en:de;if(mode==='cards')return shell(`<section class="question"><div class="small">Tap to reveal</div><div class="prompt">${esc(en)}</div><div id="reveal" hidden><div class="answer">${esc(de)}</div><div class="controls"><button class="btn bad" onclick="cardNext(false)">Still learning</button><button class="btn good" onclick="cardNext(true)">Got it</button></div></div><button id="show" class="btn" onclick="document.querySelector('#reveal').hidden=false;this.hidden=true">Show answer</button></section>`);if(mode==='choice')return choice(en,de);if(mode==='test'){let dir=Math.random()<.5?'de-en':'en-de';prompt=dir==='de-en'?de:en;target=dir==='de-en'?en:de}shell(`<section class="question"><div class="small">Translate</div><div class="prompt">${esc(prompt)}</div><input id="ans" class="input" autocomplete="off" autocapitalize="off" placeholder="Your answer…" onkeydown="if(event.key==='Enter')checkTyped('${encodeURIComponent(target)}')"><div id="feedback"></div><div class="controls"><button class="btn" onclick="checkTyped('${encodeURIComponent(target)}')">Check</button></div></section>`);setTimeout(()=>document.querySelector('#ans')?.focus(),0)}
function record(good){let p=load(current);p.seen++;if(good)p.good++;save(current,p);if(good)score++}
function cardNext(g){record(g);i++;renderQ()}function checkTyped(t){if(answered)return next();answered=true;let target=decodeURIComponent(t),input=document.querySelector('#ans').value,g=ok(input,target);record(g);document.querySelector('#feedback').innerHTML=`<div class="answer">${g?'✓ Correct!':'Not quite.'}</div>${g?'':`<div class="small">Answer: <b>${esc(target)}</b></div>`}`;document.querySelector('.controls').innerHTML=`<button class="btn" onclick="next()">Next</button>`}function next(){i++;answered=false;renderQ()}
function choice(en,de){let others=shuffle(VOCAB[current].words.filter(w=>w[1]!==de)).slice(0,3).map(w=>w[1]),opts=shuffle([de,...others]);shell(`<section class="question"><div class="small">Choose the German meaning</div><div class="prompt">${esc(en)}</div><div class="choices">${opts.map(x=>`<button class="choice" onclick="pick(this,'${encodeURIComponent(x)}','${encodeURIComponent(de)}')">${esc(x)}</button>`).join('')}</div></section>`)}function pick(btn,x,t){if(answered)return;answered=true;let g=decodeURIComponent(x)===decodeURIComponent(t);record(g);btn.classList.add(g?'correct':'wrong');[...document.querySelectorAll('.choice')].forEach(b=>{if(norm(b.textContent)===norm(decodeURIComponent(t)))b.classList.add('correct')});setTimeout(()=>{i++;answered=false;renderQ()},700)}
function match(){let pairs=shuffle(VOCAB[current].words).slice(0,Math.min(6,VOCAB[current].words.length)),items=shuffle(pairs.flatMap((w,n)=>[{text:w[0],id:n},{text:w[1],id:n}]));shell(`<section class="question"><div class="small">Tap two matching cards</div><div class="match">${items.map(x=>`<button class="choice" data-id="${x.id}" onclick="matchPick(this)">${esc(x.text)}</button>`).join('')}</div></section>`);window._match={first:null,done:0,total:pairs.length}}
function matchPick(b){let m=window._match;if(b.classList.contains('done'))return;if(!m.first){m.first=b;b.classList.add('selected');return}if(m.first===b)return;m.first.classList.remove('selected');if(m.first.dataset.id===b.dataset.id){m.first.classList.add('done');b.classList.add('done');m.done++;score++;if(m.done===m.total)setTimeout(finish,500)}else{let a=m.first;a.classList.add('wrong');b.classList.add('wrong');setTimeout(()=>{a.classList.remove('wrong');b.classList.remove('wrong')},450)}m.first=null}
function finish(){let total=mode==='match'?(window._match?.total||0):deck.length,pct=total?Math.round(score/total*100):0;shell(`<section class="question result"><div class="small">Finished!</div><div class="score">${pct}%</div><h2>${pct>=80?'Great job!':'Keep practising!'}</h2><p>${score} of ${total} correct</p><div class="controls"><button class="btn" onclick="start('${mode}')">Again</button><button class="btn secondary" onclick="openList('${current}')">Other mode</button></div></section>`)}
function route(){let h=location.hash;if(h.startsWith('#list-')){let id=h.slice(6);if(VOCAB[id])return openList(id)}if(h.startsWith('#grammar-')){let k=h.slice(9);if(GRAMMAR[k])return openGrammar(k)}if(h==='#unit4')return unit4();home()}window.addEventListener('hashchange',route);route();
