const TOPICS={
  me:{title:'Me',subtitle:'Start with yourself',words:[['name','der Name'],['age','das Alter'],['happy','glücklich'],['tired','müde'],['hungry','hungrig'],['friend','der Freund / die Freundin'],['favourite','Lieblings-'],['to like','mögen']]},
  family:{title:'My family',subtitle:'People who belong to me',words:[['family','die Familie'],['mum','die Mama'],['dad','der Papa'],['sister','die Schwester'],['brother','der Bruder'],['grandma','die Oma'],['grandpa','der Opa'],['cousin','der Cousin / die Cousine'],['parents','die Eltern'],['aunt','die Tante'],['uncle','der Onkel']]},
  school:{title:'My school',subtitle:'People, places and school life',words:[['school','die Schule'],['classroom','das Klassenzimmer'],['teacher','der Lehrer / die Lehrerin'],['lesson','die Schulstunde'],['subject','das Schulfach'],['library','die Bibliothek'],['playground','der Schulhof'],['homework','die Hausaufgabe'],['friend','der Freund / die Freundin']]},
  home:{title:'My home',subtitle:'Rooms and things at home',words:[['home','das Zuhause'],['house','das Haus'],['room','das Zimmer'],['kitchen','die Küche'],['garden','der Garten'],['living room','das Wohnzimmer'],['bathroom','das Badezimmer'],['bed','das Bett'],['door','die Tür'],['window','das Fenster']]},
  town:{title:'My town',subtitle:'Places and getting around',words:[['town','die Stadt'],['street','die Straße'],['park','der Park'],['market','der Markt'],['church','die Kirche'],['river','der Fluss'],['shop','der Laden'],['swimming pool','das Schwimmbad'],['bus stop','die Bushaltestelle'],['bridge','die Brücke']]}
};
const READINGS=[
 {id:'new-school',title:'A new school day',level:'Easy',topic:'My school',text:`Mia is eleven. Her school is near her home. On Monday morning, she walks to school with her friend Ben. Their first lesson is English. Mia likes English, but Ben likes maths more. At break time they go to the playground. After school, Mia goes to the library because she wants a new book.`,questions:[{q:'How old is Mia?',a:'eleven',options:['ten','eleven','twelve']},{q:'Who walks to school with Mia?',a:'Ben',options:['Ben','Tom','her sister']},{q:'What is their first lesson?',a:'English',options:['maths','English','German']},{q:'Where does Mia go after school?',a:'the library',options:['the park','the library','the swimming pool']}]},
 {id:'saturday-town',title:'Saturday in town',level:'Easy',topic:'My town',text:`Leo lives in a small town. On Saturday he meets his cousin at the market. First they buy two sandwiches. Then they walk past the church and go to the park. It is sunny, so they sit near the river. At four o'clock they take the bus home.`,questions:[{q:'Where does Leo meet his cousin?',a:'the market',options:['the market','the park','the bus stop']},{q:'What do they buy?',a:'two sandwiches',options:['two sandwiches','a book','ice cream']},{q:'Where do they sit?',a:'near the river',options:['near the river','in the church','at school']},{q:'How do they go home?',a:'by bus',options:['on foot','by bus','by train']}]}
];
const ROUTES=[
 {from:'School',to:'Museum',steps:[['straight'],['left','church'],['past','park'],['museum']],solution:'Go straight on. Turn left at the church. Go past the park. The museum is there.'},
 {from:'Market',to:'Swimming pool',steps:[['straight'],['right','bank'],['past','cafe'],['swimming pool']],solution:'Go straight on. Turn right at the bank. Go past the café. The swimming pool is there.'},
 {from:'Park',to:'Library',steps:[['past','church'],['left','traffic lights'],['straight'],['library']],solution:'Go past the church. Turn left at the traffic lights. Go straight on. The library is there.'}
];
function topicWords(key){return TOPICS[key]?.words||[]}
