const GRAMMAR={
 plural:{unit:1,title:'Plural nouns',subtitle:'Unit 1 · School life',intro:'Form regular and irregular plurals.',tasks:[
  {q:'one book – two ___',a:'books',hint:'Meistens kommt -s an das Wort.'},{q:'one class – two ___',a:'classes',hint:'Nach -s kommt oft -es.'},{q:'one box – three ___',a:'boxes',hint:'Nach -x kommt oft -es.'},{q:'one baby – two ___',a:'babies',hint:'Konsonant + y wird zu -ies.'},{q:'one boy – two ___',a:'boys',hint:'Vokal + y: Hänge nur -s an.'},{q:'one child – two ___',a:'children',hint:'Unregelmäßiger Plural.'},{q:'one foot – two ___',a:'feet',hint:'Unregelmäßiger Plural.'},{q:'one woman – two ___',a:'women',hint:'Unregelmäßiger Plural.'}
 ]},
 articles:{unit:1,title:'Articles: a, an & the',subtitle:'Unit 1 · School life',intro:'Choose a, an or the.',tasks:[
  {q:'This is ___ classroom.',a:'a',hint:'Ein Klassenzimmer, noch nicht näher bestimmt.'},{q:'I have ___ English book.',a:'an',hint:'Vor einem Vokallaut steht an.'},{q:'Please close ___ door.',a:'the',hint:'Wir wissen, welche Tür gemeint ist.'},{q:'Mia has ___ orange pencil case.',a:'an',hint:'orange beginnt mit einem Vokallaut.'},{q:'There is ___ computer in our room.',a:'a',hint:'Der Computer wird zum ersten Mal genannt.'},{q:'___ computer is next to the window.',a:'The',accept:['The','the'],hint:'Der Computer wurde bereits genannt.'},{q:'Ben is ___ student at our school.',a:'a',hint:'student beginnt mit einem Konsonantenlaut.'},{q:'We meet in ___ library.',a:'the',hint:'Eine bestimmte Bibliothek ist gemeint.'}
 ]},
 imperative:{unit:1,title:'Imperatives',subtitle:'Unit 1 · Classroom language',intro:'Give instructions and say what someone must not do.',tasks:[
  {q:'___ your book, please.',a:'Open',accept:['Open','open'],hint:'Öffne dein Buch.'},{q:'___ to the text.',a:'Listen',accept:['Listen','listen'],hint:'Höre dem Text zu.'},{q:'___ your name here.',a:'Write',accept:['Write','write'],hint:'Schreibe deinen Namen hierhin.'},{q:'___ quiet, please.',a:'Be',accept:['Be','be'],hint:'Sei bitte leise.'},{q:'___ run in the classroom.',a:"Don't",accept:["Don't",'Do not'],hint:'Verneinter Imperativ.'},{q:'___ your homework.',a:"Don't forget",accept:["Don't forget",'Do not forget'],hint:'Vergiss deine Hausaufgaben nicht.'},{q:'___ at page twelve.',a:'Look',accept:['Look','look'],hint:'Schau auf Seite zwölf.'},{q:'___ the question with your partner.',a:'Discuss',accept:['Discuss','discuss'],hint:'Besprecht die Frage.'}
 ]},
 pronouns:{unit:1,title:'Personal pronouns',subtitle:'Unit 1 · School life',intro:'Replace names and nouns with the right pronoun.',tasks:[
  {q:'Mia is new. ___ is in Year 5.',a:'She',accept:['She','she'],hint:'Mia = sie.'},{q:'Ben likes maths. ___ is good at it.',a:'He',accept:['He','he'],hint:'Ben = er.'},{q:'The book is blue. ___ is on the desk.',a:'It',accept:['It','it'],hint:'Für eine Sache benutzt du it.'},{q:'Mia and Ben are friends. ___ walk to school.',a:'They',accept:['They','they'],hint:'Mehrere Personen = sie.'},{q:'Sam and I are in Class 5. ___ like English.',a:'We',accept:['We','we'],hint:'Sam und ich = wir.'},{q:'“Are ___ ready, Tom?”',a:'you',accept:['you','You'],hint:'Du wirst direkt angesprochen.'},{q:'___ am eleven years old.',a:'I',hint:'Ich.'},{q:'Our school is big. ___ has a library.',a:'It',accept:['It','it'],hint:'Die Schule wird durch it ersetzt.'}
 ]},
 be:{unit:1,title:'Forms of be',subtitle:'Unit 1 · School days',intro:'Use am, is and are – including short forms.',tasks:[
  {q:'I ___ eleven years old.',a:'am',hint:'I am.'},{q:'Mia ___ in Year 5.',a:'is',hint:'he / she / it is.'},{q:'We ___ at school.',a:'are',hint:'we / you / they are.'},{q:'The books ___ on the desk.',a:'are',hint:'Mehrzahl.'},{q:'It ___ Monday.',a:'is',hint:'it is.'},{q:'I am – short form: ___',a:"I'm",hint:'Kurzform von I am.'},{q:'She is – short form: ___',a:"She's",hint:'Kurzform von she is.'},{q:'They are – short form: ___',a:"They're",hint:'Kurzform von they are.'},{q:'You ___ my partner.',a:'are',hint:'you are.'},{q:'Mr Green ___ our teacher.',a:'is',hint:'Eine Person: he is.'}
 ]},
 possessive_s:{unit:2,title:"Possessive ’s",subtitle:'Unit 2 · Family & home',intro:'Show who something belongs to.',tasks:[
  {q:'This is ___ bike. (Tom)',a:"Tom's",hint:'Das Fahrrad gehört Tom.'},{q:'That is ___ room. (Mia)',a:"Mia's",hint:'Das Zimmer gehört Mia.'},{q:'___ name is Ben. (my brother)',a:"My brother's",accept:["My brother's","my brother's"],hint:'Der Name meines Bruders.'},{q:'The ___ toys are in the box. (children)',a:"children's",hint:'children ist bereits Plural.'},{q:'This is ___ house. (Grandma)',a:"Grandma's",hint:'Omas Haus.'},{q:'Where is ___ bag? (Lucy)',a:"Lucy's",hint:'Lucys Tasche.'},{q:'The ___ classroom is upstairs. (students)',a:"students'",hint:'Mehrzahl auf -s: nur Apostroph.'},{q:'___ favourite colour is green. (Dad)',a:"Dad's",hint:'Dads Lieblingsfarbe.'}
 ]},
 be_negative:{unit:2,title:'Negative forms of be',subtitle:'Unit 2 · Family & home',intro:'Use am not, isn’t and aren’t.',tasks:[
  {q:'I ___ tired.',a:'am not',accept:['am not',"'m not"],hint:'Verneinung bei I.'},{q:'Mia ___ at home.',a:"isn't",accept:["isn't",'is not'],hint:'Verneinung bei she.'},{q:'We ___ in the kitchen.',a:"aren't",accept:["aren't",'are not'],hint:'Verneinung bei we.'},{q:'The room ___ small.',a:"isn't",accept:["isn't",'is not'],hint:'The room = it.'},{q:'They ___ brothers.',a:"aren't",accept:["aren't",'are not'],hint:'Verneinung bei they.'},{q:'You ___ late.',a:"aren't",accept:["aren't",'are not'],hint:'Verneinung bei you.'},{q:'Dad ___ in the garden.',a:"isn't",accept:["isn't",'is not'],hint:'Dad = he.'},{q:'The books ___ on the table.',a:"aren't",accept:["aren't",'are not'],hint:'Mehrzahl.'}
 ]},
 there:{unit:2,title:'There is & there are',subtitle:'Unit 2 · My home',intro:'Say what is in a room or place.',tasks:[
  {q:'___ a bed in my room.',a:'There is',accept:['There is',"There's"],hint:'Eine Sache.'},{q:'___ two windows in the kitchen.',a:'There are',hint:'Mehrere Dinge.'},{q:'___ a garden behind the house.',a:'There is',accept:['There is',"There's"],hint:'Ein Garten.'},{q:'___ three chairs at the table.',a:'There are',hint:'Drei Stühle.'},{q:'___ any posters on the wall.',a:"There aren't",accept:["There aren't",'There are not'],hint:'Verneinung in der Mehrzahl.'},{q:'___ a TV in my room.',a:"There isn't",accept:["There isn't",'There is not'],hint:'Verneinung in der Einzahl.'},{q:'___ a bathroom upstairs?',a:'Is there',hint:'Frage in der Einzahl.'},{q:'___ any books on the shelf?',a:'Are there',hint:'Frage in der Mehrzahl.'},{q:'Yes, ___.',a:'there is',hint:'Kurzantwort auf Is there …?'},{q:'No, ___.',a:"there aren't",accept:["there aren't",'there are not'],hint:'Kurzantwort auf Are there …?'}
 ]},
 be_questions:{unit:2,title:'Questions with be',subtitle:'Unit 2 · Family & home',intro:'Put am, is or are at the beginning of a question.',tasks:[
  {q:'___ you from Germany?',a:'Are',accept:['Are','are'],hint:'Frage mit you.'},{q:'___ Mia your sister?',a:'Is',accept:['Is','is'],hint:'Mia = she.'},{q:'___ they at home?',a:'Are',accept:['Are','are'],hint:'Frage mit they.'},{q:'___ the kitchen downstairs?',a:'Is',accept:['Is','is'],hint:'The kitchen = it.'},{q:'___ I in the right room?',a:'Am',accept:['Am','am'],hint:'Frage mit I.'},{q:'___ your parents at work?',a:'Are',accept:['Are','are'],hint:'parents ist Mehrzahl.'},{q:'“Is Ben eleven?” – “Yes, ___.”',a:'he is',hint:'Positive Kurzantwort.'},{q:'“Are you tired?” – “No, ___.”',a:"I'm not",accept:["I'm not",'I am not'],hint:'Negative Kurzantwort.'}
 ]},
 question_words:{unit:2,title:'Question words',subtitle:'Unit 2 · Family & home',intro:'Choose who, what, where, when, why or how.',tasks:[
  {q:'___ is your name?',a:'What',accept:['What','what'],hint:'Frage nach einer Sache oder Information.'},{q:'___ do you live?',a:'Where',accept:['Where','where'],hint:'Frage nach einem Ort.'},{q:'___ is that girl?',a:'Who',accept:['Who','who'],hint:'Frage nach einer Person.'},{q:'___ old are you?',a:'How',accept:['How','how'],hint:'How old …?'},{q:'___ is your birthday?',a:'When',accept:['When','when'],hint:'Frage nach einem Zeitpunkt.'},{q:'___ are you happy?',a:'Why',accept:['Why','why'],hint:'Frage nach einem Grund.'},{q:'___ many brothers have you got?',a:'How',accept:['How','how'],hint:'How many …?'},{q:'___ is your favourite room?',a:'What',accept:['What','what'],hint:'Frage nach einer Auswahl.'}
 ]},
 prep:{unit:4,title:'Prepositions of place & movement',subtitle:'Unit 4 · Where I live',intro:'Practise where things are and how to describe movement.',tasks:[
  {q:'The café is ___ the bank and the supermarket.',a:'between',hint:'zwischen'},{q:'The museum is ___ the park.',a:'opposite',hint:'gegenüber'},{q:'Walk ___ the bridge.',a:'over',hint:'über die Brücke'},{q:'Go ___ the tunnel.',a:'through',hint:'durch den Tunnel'},{q:'Walk ___ the river.',a:'along',hint:'am Fluss entlang'},{q:'Turn left ___ the traffic lights.',a:'at',hint:'an der Ampel'},{q:'The bus stop is ___ the right.',a:'on',hint:'auf der rechten Seite'},{q:'Go straight on ___ the crossing.',a:'until',hint:'bis zur Kreuzung'},{q:'Turn right ___ King Street.',a:'into',hint:'in die King Street hinein'},{q:'The church is ___ the market.',a:'next to',hint:'neben dem Markt'}
 ]},
 place_time:{unit:4,title:'Place before time',subtitle:'Unit 4 · Where and when?',intro:'Put the place before the time in an English sentence.',tasks:[
  {q:'We meet ___ the park at three o’clock.',a:'in',hint:'Ort steht vor Zeit: im Park um drei.'},{q:'Mia is ___ the youth club on Friday.',a:'at',hint:'Ort steht vor Zeit.'},{q:'They play football ___ the sports centre after school.',a:'at',hint:'Zuerst der Ort, dann die Zeit.'},{q:'I go swimming ___ the pool on Saturday.',a:'at',hint:'Ort vor Zeit.'},{q:'Put in order: We meet / at four / at the café.',a:'We meet at the café at four',accept:['We meet at the café at four','We meet at the café at four o’clock'],hint:'Place before time.'},{q:'Put in order: on Monday / Ben is / at school.',a:'Ben is at school on Monday',hint:'Place before time.'},{q:'Put in order: in the park / after lunch / They play.',a:'They play in the park after lunch',hint:'Place before time.'},{q:'Put in order: at six / The film starts / at the cinema.',a:'The film starts at the cinema at six',hint:'Place before time.'}
 ]},
 directions:{unit:4,title:'Giving directions',subtitle:'Unit 4 · Getting around',intro:'Build useful sentences for giving directions.',tasks:[
  {q:'___ straight on.',a:'Go',accept:['Go'],hint:'Geradeaus gehen.'},{q:'___ left at the crossing.',a:'Turn',accept:['Turn','Go'],hint:'An der Kreuzung links abbiegen.'},{q:'Go straight on ___ you get to the park.',a:'until',hint:'… bis du zum Park kommst.'},{q:'The café is ___ your left.',a:'on',hint:'Das Café ist auf deiner linken Seite.'},{q:'Go ___ the roundabout.',a:'round',accept:['round','around'],hint:'Geh um den Kreisverkehr herum.'},{q:'___ the road at the traffic lights.',a:'Cross',accept:['Cross'],hint:'Überquere die Straße an der Ampel.'},{q:'Walk ___ the road for two minutes.',a:'along',hint:'Geh die Straße entlang.'},{q:'Go ___ the first street on the right.',a:'into',accept:['into','down'],hint:'Geh in die erste Straße rechts.'}
 ]},
 simple_past:{unit:5,title:'Simple past',subtitle:'Unit 5 · Around the year',intro:'Talk about things that happened in the past.',tasks:[
  {q:'Yesterday I ___ football. (play)',a:'played',hint:'Regelmäßiges Verb: -ed.'},{q:'Mia ___ her grandma. (visit)',a:'visited',hint:'Regelmäßiges Verb: -ed.'},{q:'We ___ a film last night. (watch)',a:'watched',hint:'Regelmäßiges Verb: -ed.'},{q:'They ___ to the park. (go)',a:'went',hint:'Unregelmäßiges Verb.'},{q:'Ben ___ a sandwich. (eat)',a:'ate',hint:'Unregelmäßiges Verb.'},{q:'I ___ my friend in town. (see)',a:'saw',hint:'Unregelmäßiges Verb.'},{q:'She ___ a postcard. (write)',a:'wrote',hint:'Unregelmäßiges Verb.'},{q:'Dad ___ a photo. (take)',a:'took',hint:'Unregelmäßiges Verb.'},{q:'It ___ sunny yesterday. (be)',a:'was',hint:'Simple past von is.'},{q:'We ___ at home. (be)',a:'were',hint:'Simple past von are.'}
 ]},
 simple_past_negative:{unit:5,title:'Simple past – negative',subtitle:'Unit 5 · Around the year',intro:'Say what did not happen.',tasks:[
  {q:'I ___ football yesterday. (not play)',a:"didn't play",accept:["didn't play",'did not play'],hint:'didn’t + Grundform.'},{q:'Mia ___ her grandma. (not visit)',a:"didn't visit",accept:["didn't visit",'did not visit'],hint:'didn’t + Grundform.'},{q:'We ___ to the park. (not go)',a:"didn't go",accept:["didn't go",'did not go'],hint:'Nach didn’t steht go, nicht went.'},{q:'Ben ___ the film. (not watch)',a:"didn't watch",accept:["didn't watch",'did not watch'],hint:'didn’t + Grundform.'},{q:'They ___ breakfast. (not eat)',a:"didn't eat",accept:["didn't eat",'did not eat'],hint:'Nach didn’t steht eat.'},{q:'I ___ tired yesterday. (not be)',a:"wasn't",accept:["wasn't",'was not'],hint:'Verneinung von was.'},{q:'We ___ at school. (not be)',a:"weren't",accept:["weren't",'were not'],hint:'Verneinung von were.'},{q:'It ___ cold last week. (not be)',a:"wasn't",accept:["wasn't",'was not'],hint:'Verneinung von was.'}
 ]}
};
